version: "2"

services:
  api:
    image: api
    ports: ["8081:8081"]
    environment:
      - "SOME_ENV=some_env"
    volumes_from:
      - data
    stdin_open: true
    container_name: api


  data:
    image: data
    ports: ["8084:8084"]
    environment:
      - "SOME_ENV=some_env"
    volumes:
      - ./front:/app
    stdin_open: true
    container_name: data
