FROM ubuntu

RUN apt update
RUN apt -y upgrade
RUN apt install -y vim
RUN apt install -y curl
RUN apt-get update
RUN apt-get install -y iputils-ping
RUN apt install -y python3.6 python3-pip

RUN mkdir /app

